# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d5dc30fc05f6ccf95dba313d17ac2b96fe972f5b8389868261c2c37790154cf9d695f9406fb095c424a22dfcf050ed21dabe33dd86681c16047491058c357c6

test:
  secret_key_base: e38b8a11c3bf072d0f0a905d6463d16690c0882544f59a98b308ff5cb0de15a6b993f69f0ae86a27b89ac3321b08e5c7d3d30398933b63a7b6b3d3185f455a25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
